const resolvers = {
    Query: {
        offers(parent, args, contextValue, info) {
            return data;
        },
    },
    Mutation: {
        markVisited(parent, args, contextValue, info) {
            return data.find(item => item.id === args.id)
        }
    }
}

module.exports = resolvers

const data = [{
        "id": "RU",
        "name": "Russia",
        "imageUrl": "http://dummyimage.com/243x100.png/5fa2dd/ffffff",
        "dateAdded": "12/09/2022",
        "description": "SE",
        "value": 63,
        "currency": "RUB",
        "visitedCount": 1
    }, {
        "id": "NO",
        "name": "Norway",
        "imageUrl": "http://dummyimage.com/175x100.png/dddddd/000000",
        "dateAdded": "04/10/2022",
        "description": "RU",
        "value": 48,
        "currency": "NOK",
        "visitedCount": 2
    }, {
        "id": "BR",
        "name": "Brazil",
        "imageUrl": "http://dummyimage.com/215x100.png/cc0000/ffffff",
        "dateAdded": "14/06/2022",
        "description": "CA",
        "value": 17,
        "currency": "BRL",
        "visitedCount": 3
    }, {
        "id": "US",
        "name": "United States",
        "imageUrl": "http://dummyimage.com/244x100.png/dddddd/000000",
        "dateAdded": "09/11/2022",
        "description": "AU",
        "value": 22,
        "currency": "USD",
        "visitedCount": 4
    }, {
        "id": "SE",
        "name": "Sweden",
        "imageUrl": "http://dummyimage.com/247x100.png/dddddd/000000",
        "dateAdded": "14/11/2022",
        "description": "GR",
        "value": 2,
        "currency": "SEK",
        "visitedCount": 5
    }, {
        "id": "TG",
        "name": "Togo",
        "imageUrl": "http://dummyimage.com/119x100.png/ff4444/ffffff",
        "dateAdded": "16/06/2022",
        "description": "ZA",
        "value": 60,
        "currency": "XOF",
        "visitedCount": 6
    }, {
        "id": "SE",
        "name": "Sweden",
        "imageUrl": "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
        "dateAdded": "11/01/2023",
        "description": "CN",
        "value": 67,
        "currency": "SEK",
        "visitedCount": 7
    }, {
        "id": "FR",
        "name": "France",
        "imageUrl": "http://dummyimage.com/223x100.png/ff4444/ffffff",
        "dateAdded": "24/07/2022",
        "description": "PR",
        "value": 14,
        "currency": "EUR",
        "visitedCount": 8
    }, {
        "id": "PT",
        "name": "Portugal",
        "imageUrl": "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
        "dateAdded": "26/03/2022",
        "description": "MM",
        "value": 8,
        "currency": "EUR",
        "visitedCount": 9
    }, {
        "id": "CN",
        "name": "China",
        "imageUrl": "http://dummyimage.com/236x100.png/dddddd/000000",
        "dateAdded": "20/09/2022",
        "description": "US",
        "value": 48,
        "currency": "CNY",
        "visitedCount": 10
    }, {
        "id": "CN",
        "name": "China",
        "imageUrl": "http://dummyimage.com/153x100.png/ff4444/ffffff",
        "dateAdded": "17/03/2022",
        "description": "NA",
        "value": 22,
        "currency": "CNY",
        "visitedCount": 11
    }, {
        "id": "ID",
        "name": "Indonesia",
        "imageUrl": "http://dummyimage.com/163x100.png/cc0000/ffffff",
        "dateAdded": "11/11/2022",
        "description": "PG",
        "value": 80,
        "currency": "IDR",
        "visitedCount": 12
    }, {
        "id": "NC",
        "name": "New Caledonia",
        "imageUrl": "http://dummyimage.com/165x100.png/5fa2dd/ffffff",
        "dateAdded": "03/10/2022",
        "description": "UA",
        "value": 70,
        "currency": "XPF",
        "visitedCount": 13
    }, {
        "id": "PH",
        "name": "Philippines",
        "imageUrl": "http://dummyimage.com/107x100.png/dddddd/000000",
        "dateAdded": "30/10/2022",
        "description": "RU",
        "value": 61,
        "currency": "PHP",
        "visitedCount": 14
    }, {
        "id": "ID",
        "name": "Indonesia",
        "imageUrl": "http://dummyimage.com/161x100.png/ff4444/ffffff",
        "dateAdded": "02/03/2023",
        "description": "CA",
        "value": 99,
        "currency": "IDR",
        "visitedCount": 15
    }, {
        "id": "CN",
        "name": "China",
        "imageUrl": "http://dummyimage.com/219x100.png/dddddd/000000",
        "dateAdded": "24/11/2022",
        "description": "RU",
        "value": 9,
        "currency": "CNY",
        "visitedCount": 16
    }, {
        "id": "PT",
        "name": "Portugal",
        "imageUrl": "http://dummyimage.com/103x100.png/cc0000/ffffff",
        "dateAdded": "01/01/2023",
        "description": "CA",
        "value": 20,
        "currency": "EUR",
        "visitedCount": 17
    }, {
        "id": "BS",
        "name": "Bahamas",
        "imageUrl": "http://dummyimage.com/203x100.png/cc0000/ffffff",
        "dateAdded": "01/11/2022",
        "description": "GL",
        "value": 88,
        "currency": "BSD",
        "visitedCount": 18
    }, {
        "id": "TG",
        "name": "Togo",
        "imageUrl": "http://dummyimage.com/110x100.png/5fa2dd/ffffff",
        "dateAdded": "02/08/2022",
        "description": "ID",
        "value": 76,
        "currency": "XOF",
        "visitedCount": 19
    }, {
        "id": "CN",
        "name": "China",
        "imageUrl": "http://dummyimage.com/182x100.png/5fa2dd/ffffff",
        "dateAdded": "30/03/2022",
        "description": "CN",
        "value": 51,
        "currency": "CNY",
        "visitedCount": 20
    }, {
        "id": "EG",
        "name": "Egypt",
        "imageUrl": "http://dummyimage.com/214x100.png/5fa2dd/ffffff",
        "dateAdded": "28/08/2022",
        "description": "GA",
        "value": 33,
        "currency": "EGP",
        "visitedCount": 21
    }, {
        "id": "RU",
        "name": "Russia",
        "imageUrl": "http://dummyimage.com/209x100.png/cc0000/ffffff",
        "dateAdded": "13/09/2022",
        "description": "US",
        "value": 100,
        "currency": "RUB",
        "visitedCount": 22
    }, {
        "id": "ID",
        "name": "Indonesia",
        "imageUrl": "http://dummyimage.com/129x100.png/dddddd/000000",
        "dateAdded": "09/06/2022",
        "description": "RU",
        "value": 64,
        "currency": "IDR",
        "visitedCount": 23
    }, {
        "id": "PH",
        "name": "Philippines",
        "imageUrl": "http://dummyimage.com/244x100.png/5fa2dd/ffffff",
        "dateAdded": "08/07/2022",
        "description": "ET",
        "value": 29,
        "currency": "PHP",
        "visitedCount": 24
    }, {
        "id": "NL",
        "name": "Netherlands",
        "imageUrl": "http://dummyimage.com/125x100.png/cc0000/ffffff",
        "dateAdded": "13/06/2022",
        "description": "BS",
        "value": 90,
        "currency": "EUR",
        "visitedCount": 25
    }];
